"""Phase D1: SEBI algo-order tagging.

SEBI's retail algorithmic-trading framework (circular of February 2025, in force from
August 2025) requires every order generated by an algorithm to carry the algo identifier the
exchange issued when the broker registered that algo, so the exchange can attribute every algo
order to a registered strategy. Brokers expose that through the free-text order `tag` (Zerodha,
Upstox) or `remarks` (Shoonya) field.

Every broker order this platform places - entry, protective stop, exit - therefore goes through
`build_order_tag`, which composes `<algo id>-<strategy>-<leg>` inside the broker's tag length
limit, keeping the algo id and the leg intact and shortening only the strategy part. The tag
the broker actually received is stored on the order row (`orders.algo_tag`) so the platform's
own order trail and the exchange's records can be reconciled. The algo id itself is tenant
configuration (`tenants.algo_id`, set by an OWNER on the Team page after the broker registers
the algo); without one, tags fall back to `<strategy>-<leg>` and - when
`ALGO_ID_REQUIRED_FOR_LIVE` is on - LIVE orders are refused before they reach the broker.
"""
import re
from typing import Optional

# Conservative default: Zerodha documents `tag` as alphanumeric, at most 20 characters, and
# every other adapter accepts at least that. Adapters raise `max_tag_length` where they can.
DEFAULT_MAX_TAG_LENGTH = 20

ALGO_ID_PATTERN = re.compile(r"^[A-Za-z0-9_-]{1,32}$")

_UNSAFE = re.compile(r"[^A-Za-z0-9_-]+")

LEG_ENTRY = "ENT"
LEG_STOP = "SL"
LEG_EXIT = "EXIT"


def sanitize_tag_part(value: str) -> str:
    """Broker tag fields reject most punctuation and whitespace; keep letters, digits, `_`, `-`."""
    return _UNSAFE.sub("", value or "")


def valid_algo_id(value: str) -> bool:
    return bool(ALGO_ID_PATTERN.match(value or ""))


def build_order_tag(
    *, strategy_id: str, leg: str, algo_id: Optional[str] = None, max_length: int = DEFAULT_MAX_TAG_LENGTH,
) -> str:
    """`<algo_id>-<strategy>-<leg>` shortened to `max_length`, dropping strategy characters first
    (the algo id is the compliance value and the leg is what reconciliation keys on), then, if
    the algo id and leg alone still do not fit, the leg is truncated last."""
    algo = sanitize_tag_part(algo_id or "")
    leg_part = sanitize_tag_part(leg).upper() or LEG_ENTRY
    strategy = sanitize_tag_part(strategy_id)

    fixed = [p for p in (algo, leg_part) if p]
    fixed_len = sum(len(p) for p in fixed) + (len(fixed) - 1)  # separators between fixed parts
    room_for_strategy = max_length - fixed_len - 1  # one more separator for the strategy part
    if room_for_strategy >= 1 and strategy:
        parts = [algo, strategy[:room_for_strategy], leg_part] if algo else [strategy[:room_for_strategy], leg_part]
    else:
        parts = fixed
    tag = "-".join(p for p in parts if p)
    return tag[:max_length]
