// P1.2: writes src/styles/palette.css - the Tailwind hues the pages use, as CSS variables, so a theme can remap them.
// Dark (default): Tailwind's own values. Light: text and border shades are mirrored (300 <-> 700, 200 <-> 800...)
// so light-on-dark text stays readable on a light surface; backgrounds keep Tailwind's values (a solid green button
// stays green). Colour-blind mode: emerald/green read as blue and rose/red as orange. Run: node scripts/gen-palette.mjs
import { writeFileSync } from "node:fs";
import colors from "tailwindcss/colors.js";

export const HUES = ["slate", "emerald", "green", "rose", "red", "amber", "yellow", "orange", "sky", "blue", "cyan", "teal",
  "lime", "indigo", "violet", "purple", "fuchsia", "pink"];
const SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const MIRROR = Object.fromEntries(SHADES.map((s, i) => [s, SHADES[SHADES.length - 1 - i]]));
const CVD = { emerald: "blue", green: "blue", rose: "orange", red: "orange" };

const rgb = (hex) => {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(" ");
};
const block = (sel, lines) => `${sel} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}\n`;
const vars = (prefix, pick) => HUES.flatMap((hue) => SHADES.map((s) => `--${prefix}-${hue}-${s}: ${pick(hue, s)};`));

const out = [
  "/* Generated by scripts/gen-palette.mjs - do not edit by hand. */",
  block(":root", [
    ...vars("tx", (h, s) => rgb(colors[h][s])),
    ...vars("bgc", (h, s) => rgb(colors[h][s])),
  ]),
  block(':root[data-theme="light"]', [
    ...vars("tx", (h, s) => rgb(colors[h][MIRROR[s]])),
    // A light theme's slate backgrounds are mirrored too (bg-slate-800 chips become light chips).
    ...SHADES.map((s) => `--bgc-slate-${s}: ${rgb(colors.slate[MIRROR[s]])};`),
  ]),
  block(':root[data-cvd="on"]', Object.entries(CVD).flatMap(([h, to]) =>
    SHADES.flatMap((s) => [`--tx-${h}-${s}: ${rgb(colors[to][s])};`, `--bgc-${h}-${s}: ${rgb(colors[to][s])};`]))),
  block(':root[data-theme="light"][data-cvd="on"]', Object.entries(CVD).flatMap(([h, to]) =>
    SHADES.map((s) => `--tx-${h}-${s}: ${rgb(colors[to][MIRROR[s]])};`))),
].join("\n");
writeFileSync(new URL("../src/styles/palette.css", import.meta.url), out);
console.log(`palette.css: ${HUES.length} hues x ${SHADES.length} shades`);
