"""add earnings calendar events

Revision ID: a4776c6cc478
Revises: fb1a2134bd48
Create Date: 2026-09-12 05:31:57.404165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4776c6cc478'
down_revision: Union[str, Sequence[str], None] = 'fb1a2134bd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_calendar_events_company_id'), 'earnings_calendar_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_events_event_date'), 'earnings_calendar_events', ['event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_calendar_events_event_date'), table_name='earnings_calendar_events')
    op.drop_index(op.f('ix_earnings_calendar_events_company_id'), table_name='earnings_calendar_events')
    op.drop_table('earnings_calendar_events')
    # ### end Alembic commands ###
