"""add fundamental analysis tables

Revision ID: b556918a3e04
Revises: b95b09806938
Create Date: 2026-09-12 05:03:30.251486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b556918a3e04'
down_revision: Union[str, Sequence[str], None] = 'b95b09806938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bse_code', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('cap_category', sa.String(length=20), nullable=True),
    sa.Column('promoter_holding_pct', sa.Float(), nullable=True),
    sa.Column('fii_holding_pct', sa.Float(), nullable=True),
    sa.Column('dii_holding_pct', sa.Float(), nullable=True),
    sa.Column('public_holding_pct', sa.Float(), nullable=True),
    sa.Column('promoter_pledge_pct', sa.Float(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('business_segments_json', sa.Text(), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('domestic_revenue_pct', sa.Float(), nullable=True),
    sa.Column('international_revenue_pct', sa.Float(), nullable=True),
    sa.Column('cyclical', sa.Boolean(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('announced_date', sa.Date(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_revenue_impact', sa.String(length=20), nullable=True),
    sa.Column('expected_margin_impact', sa.String(length=20), nullable=True),
    sa.Column('expected_eps_impact', sa.String(length=20), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_company_id'), 'corporate_actions', ['company_id'], unique=False)
    op.create_table('financial_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('cogs', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=False),
    sa.Column('depreciation', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=False),
    sa.Column('exceptional_items', sa.Float(), nullable=False),
    sa.Column('tax_expense', sa.Float(), nullable=True),
    sa.Column('pat', sa.Float(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('cfo', sa.Float(), nullable=True),
    sa.Column('cfi', sa.Float(), nullable=True),
    sa.Column('cff', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('receivables', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('payables', sa.Float(), nullable=True),
    sa.Column('contingent_liabilities', sa.Float(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'period_label', name='uq_company_period')
    )
    op.create_index(op.f('ix_financial_periods_company_id'), 'financial_periods', ['company_id'], unique=False)
    op.create_table('qualitative_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualitative_factors_company_id'), 'qualitative_factors', ['company_id'], unique=False)
    op.create_table('shareholding_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('promoter_pct', sa.Float(), nullable=False),
    sa.Column('promoter_pledge_pct', sa.Float(), nullable=False),
    sa.Column('fii_pct', sa.Float(), nullable=True),
    sa.Column('dii_pct', sa.Float(), nullable=True),
    sa.Column('public_pct', sa.Float(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareholding_snapshots_company_id'), 'shareholding_snapshots', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shareholding_snapshots_company_id'), table_name='shareholding_snapshots')
    op.drop_table('shareholding_snapshots')
    op.drop_index(op.f('ix_qualitative_factors_company_id'), table_name='qualitative_factors')
    op.drop_table('qualitative_factors')
    op.drop_index(op.f('ix_financial_periods_company_id'), table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_index(op.f('ix_corporate_actions_company_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
