"""add risk settings

Revision ID: b95b09806938
Revises: bfcad91e7244
Create Date: 2026-09-12 00:12:52.844154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95b09806938'
down_revision: Union[str, Sequence[str], None] = 'bfcad91e7244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('min_risk_reward', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_settings_user_id'), 'risk_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_settings_user_id'), table_name='risk_settings')
    op.drop_table('risk_settings')
    # ### end Alembic commands ###
