"""add mfa

Revision ID: c5f1a8d3e927
Revises: b9e4c2d7a316
Create Date: 2026-09-26 12:40:27.413720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f1a8d3e927'
down_revision: Union[str, Sequence[str], None] = 'b9e4c2d7a316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_backup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_backup_codes_code_hash'), 'mfa_backup_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_mfa_backup_codes_user_id'), 'mfa_backup_codes', ['user_id'], unique=False)
    op.add_column('tenants', sa.Column('require_mfa_for_live', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_sessions', sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled_at')
    op.drop_column('users', 'mfa_secret_encrypted')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('user_sessions', 'mfa_verified_at')
    op.drop_column('tenants', 'require_mfa_for_live')
    op.drop_index(op.f('ix_mfa_backup_codes_user_id'), table_name='mfa_backup_codes')
    op.drop_index(op.f('ix_mfa_backup_codes_code_hash'), table_name='mfa_backup_codes')
    op.drop_table('mfa_backup_codes')
    # ### end Alembic commands ###
