"""add alert channels and deliveries

Revision ID: e3b8d1c7a942
Revises: d2a7c9e4f581
Create Date: 2026-09-26 11:32:02.398301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b8d1c7a942'
down_revision: Union[str, Sequence[str], None] = 'd2a7c9e4f581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_severity', sa.String(length=10), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel_type', name='uq_alert_channel_tenant_type')
    )
    op.create_index(op.f('ix_alert_channels_tenant_id'), 'alert_channels', ['tenant_id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['alert_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_channel_id'), 'alert_deliveries', ['channel_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_notification_id'), 'alert_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_status'), 'alert_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_tenant_id'), 'alert_deliveries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_deliveries_tenant_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_status'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_notification_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_channel_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_alert_channels_tenant_id'), table_name='alert_channels')
    op.drop_table('alert_channels')
    # ### end Alembic commands ###
