"""add team invites, per-user notification reads, users.is_active; promote each tenant's first user to OWNER

Revision ID: f4c2a9e1b753
Revises: e3b8d1c7a942
Create Date: 2026-09-26 11:41:13.694267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c2a9e1b753'
down_revision: Union[str, Sequence[str], None] = 'e3b8d1c7a942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_tenant_invites_email'), 'tenant_invites', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_invites_tenant_id'), 'tenant_invites', ['tenant_id'], unique=False)
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_read_user')
    )
    op.create_index(op.f('ix_notification_reads_notification_id'), 'notification_reads', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_reads_user_id'), 'notification_reads', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # Data migration. Until now every tenant had exactly one user, created by /register with role
    # USER. That user is the tenant's owner in every sense, so promote the earliest USER of each
    # tenant to OWNER - otherwise no existing tenant could invite anyone. Users already holding
    # SUPER_ADMIN/STRATEGY_CREATOR/SUPPORT are left untouched.
    bind = op.get_bind()
    users = sa.table('users', sa.column('id', sa.Integer()), sa.column('tenant_id', sa.Integer()), sa.column('role', sa.String()))
    earliest = bind.execute(
        sa.select(users.c.tenant_id, sa.func.min(users.c.id)).where(users.c.role == 'USER').group_by(users.c.tenant_id)
    ).fetchall()
    for tenant_id, user_id in earliest:
        bind.execute(users.update().where(users.c.id == user_id).values(role='OWNER'))

    # Notifications previously marked read via the single `read_at` column were read by that same
    # one user; carry that over so nobody's inbox suddenly fills with old alerts.
    notifications = sa.table(
        'notifications', sa.column('id', sa.Integer()), sa.column('tenant_id', sa.Integer()), sa.column('read_at', sa.DateTime()),
    )
    reads = sa.table(
        'notification_reads', sa.column('notification_id', sa.Integer()), sa.column('user_id', sa.Integer()), sa.column('read_at', sa.DateTime()),
    )
    first_user_by_tenant = dict(bind.execute(sa.select(users.c.tenant_id, sa.func.min(users.c.id)).group_by(users.c.tenant_id)).fetchall())
    read_rows = bind.execute(
        sa.select(notifications.c.id, notifications.c.tenant_id, notifications.c.read_at).where(notifications.c.read_at.is_not(None))
    ).fetchall()
    for notification_id, tenant_id, read_at in read_rows:
        user_id = first_user_by_tenant.get(tenant_id)
        if user_id is not None:
            bind.execute(reads.insert().values(notification_id=notification_id, user_id=user_id, read_at=read_at))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_notification_reads_user_id'), table_name='notification_reads')
    op.drop_index(op.f('ix_notification_reads_notification_id'), table_name='notification_reads')
    op.drop_table('notification_reads')
    op.drop_index(op.f('ix_tenant_invites_tenant_id'), table_name='tenant_invites')
    op.drop_index(op.f('ix_tenant_invites_email'), table_name='tenant_invites')
    op.drop_table('tenant_invites')
    # ### end Alembic commands ###
