"""add shareholders equity and total assets to financial periods

Revision ID: fb1a2134bd48
Revises: b556918a3e04
Create Date: 2026-09-12 05:11:56.475536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1a2134bd48'
down_revision: Union[str, Sequence[str], None] = 'b556918a3e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_periods', sa.Column('shareholders_equity', sa.Float(), nullable=True))
    op.add_column('financial_periods', sa.Column('total_assets', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_periods', 'total_assets')
    op.drop_column('financial_periods', 'shareholders_equity')
    # ### end Alembic commands ###
